// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.demo.protobuf;

public final class DemoProtoBuf {
  private DemoProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Demo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 默认就是singular  最多出现1次
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    String getValue();
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    com.google.protobuf.ByteString
        getValueBytes();

    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @return A list containing the likes.
     */
    java.util.List<String>
        getLikesList();
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @return The count of likes.
     */
    int getLikesCount();
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @param index The index of the element to return.
     * @return The likes at the given index.
     */
    String getLikes(int index);
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the likes at the given index.
     */
    com.google.protobuf.ByteString
        getLikesBytes(int index);
  }
  /**
   * <pre>
   * 每个字段必须要有编号，并且不允许重复
   * </pre>
   *
   * Protobuf type {@code Demo}
   */
  public  static final class Demo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Demo)
      DemoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo.newBuilder() to construct.
    private Demo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo() {
      value_ = "";
      likes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Demo();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                likes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              likes_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          likes_ = likes_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DemoProtoBuf.internal_static_Demo_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DemoProtoBuf.internal_static_Demo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DemoProtoBuf.Demo.class, DemoProtoBuf.Demo.Builder.class);
    }

    /**
     * <pre>
     * 保留值
     * 功能:设置一些不可以被定义的值，即保留不允许被使用 （reserved）
     * 1 指定 保留字段编号
     * 2 指定 保留字段名
     * </pre>
     *
     * Protobuf enum {@code Demo.Color}
     */
    public enum Color
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RED = 0;</code>
       */
      RED(0),
      /**
       * <pre>
       * 字段编号4 和 BLACK 已经被reserved 不能再被定义，编译报错(reserved 的作用)
       * BLUE = 4;
       * BLACK = 8;
       * </pre>
       *
       * <code>BLUE = 7;</code>
       */
      BLUE(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RED = 0;</code>
       */
      public static final int RED_VALUE = 0;
      /**
       * <pre>
       * 字段编号4 和 BLACK 已经被reserved 不能再被定义，编译报错(reserved 的作用)
       * BLUE = 4;
       * BLACK = 8;
       * </pre>
       *
       * <code>BLUE = 7;</code>
       */
      public static final int BLUE_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Color valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Color forNumber(int value) {
        switch (value) {
          case 0: return RED;
          case 7: return BLUE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Color>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Color> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Color>() {
              public Color findValueByNumber(int number) {
                return Color.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return DemoProtoBuf.Demo.getDescriptor().getEnumTypes().get(0);
      }

      private static final Color[] VALUES = values();

      public static Color valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Color(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Demo.Color)
    }

    public interface DemoMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Demo.DemoMessage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>.Demo.Color color = 1;</code>
       * @return The enum numeric value on the wire for color.
       */
      int getColorValue();
      /**
       * <code>.Demo.Color color = 1;</code>
       * @return The color.
       */
      DemoProtoBuf.Demo.Color getColor();

      /**
       * <code>int32 messageData = 2;</code>
       * @return The messageData.
       */
      int getMessageData();
    }
    /**
     * <pre>
     * 枚举类一般配合其它消息类型使用
     *  message 里面的字段不能从0开始,
     *并且proto3 里面舍弃了default，即不能设置default
     * </pre>
     *
     * Protobuf type {@code Demo.DemoMessage}
     */
    public  static final class DemoMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Demo.DemoMessage)
        DemoMessageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DemoMessage.newBuilder() to construct.
      private DemoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DemoMessage() {
        color_ = 0;
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new DemoMessage();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DemoMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int rawValue = input.readEnum();

                color_ = rawValue;
                break;
              }
              case 16: {

                messageData_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoProtoBuf.internal_static_Demo_DemoMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoProtoBuf.internal_static_Demo_DemoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoProtoBuf.Demo.DemoMessage.class, DemoProtoBuf.Demo.DemoMessage.Builder.class);
      }

      public static final int COLOR_FIELD_NUMBER = 1;
      private int color_;
      /**
       * <code>.Demo.Color color = 1;</code>
       * @return The enum numeric value on the wire for color.
       */
      public int getColorValue() {
        return color_;
      }
      /**
       * <code>.Demo.Color color = 1;</code>
       * @return The color.
       */
      public DemoProtoBuf.Demo.Color getColor() {
        @SuppressWarnings("deprecation")
        DemoProtoBuf.Demo.Color result = DemoProtoBuf.Demo.Color.valueOf(color_);
        return result == null ? DemoProtoBuf.Demo.Color.UNRECOGNIZED : result;
      }

      public static final int MESSAGEDATA_FIELD_NUMBER = 2;
      private int messageData_;
      /**
       * <code>int32 messageData = 2;</code>
       * @return The messageData.
       */
      public int getMessageData() {
        return messageData_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (color_ != DemoProtoBuf.Demo.Color.RED.getNumber()) {
          output.writeEnum(1, color_);
        }
        if (messageData_ != 0) {
          output.writeInt32(2, messageData_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (color_ != DemoProtoBuf.Demo.Color.RED.getNumber()) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, color_);
        }
        if (messageData_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, messageData_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof DemoProtoBuf.Demo.DemoMessage)) {
          return super.equals(obj);
        }
        DemoProtoBuf.Demo.DemoMessage other = (DemoProtoBuf.Demo.DemoMessage) obj;

        if (color_ != other.color_) return false;
        if (getMessageData()
            != other.getMessageData()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + COLOR_FIELD_NUMBER;
        hash = (53 * hash) + color_;
        hash = (37 * hash) + MESSAGEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getMessageData();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static DemoProtoBuf.Demo.DemoMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(DemoProtoBuf.Demo.DemoMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * <pre>
       * 枚举类一般配合其它消息类型使用
       *  message 里面的字段不能从0开始,
       *并且proto3 里面舍弃了default，即不能设置default
       * </pre>
       *
       * Protobuf type {@code Demo.DemoMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Demo.DemoMessage)
          DemoProtoBuf.Demo.DemoMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DemoProtoBuf.internal_static_Demo_DemoMessage_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DemoProtoBuf.internal_static_Demo_DemoMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DemoProtoBuf.Demo.DemoMessage.class, DemoProtoBuf.Demo.DemoMessage.Builder.class);
        }

        // Construct using com.demo.protobuf.DemoProtoBuf.Demo.DemoMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          color_ = 0;

          messageData_ = 0;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DemoProtoBuf.internal_static_Demo_DemoMessage_descriptor;
        }

        @Override
        public DemoProtoBuf.Demo.DemoMessage getDefaultInstanceForType() {
          return DemoProtoBuf.Demo.DemoMessage.getDefaultInstance();
        }

        @Override
        public DemoProtoBuf.Demo.DemoMessage build() {
          DemoProtoBuf.Demo.DemoMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public DemoProtoBuf.Demo.DemoMessage buildPartial() {
          DemoProtoBuf.Demo.DemoMessage result = new DemoProtoBuf.Demo.DemoMessage(this);
          result.color_ = color_;
          result.messageData_ = messageData_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DemoProtoBuf.Demo.DemoMessage) {
            return mergeFrom((DemoProtoBuf.Demo.DemoMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DemoProtoBuf.Demo.DemoMessage other) {
          if (other == DemoProtoBuf.Demo.DemoMessage.getDefaultInstance()) return this;
          if (other.color_ != 0) {
            setColorValue(other.getColorValue());
          }
          if (other.getMessageData() != 0) {
            setMessageData(other.getMessageData());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DemoProtoBuf.Demo.DemoMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DemoProtoBuf.Demo.DemoMessage) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int color_ = 0;
        /**
         * <code>.Demo.Color color = 1;</code>
         * @return The enum numeric value on the wire for color.
         */
        public int getColorValue() {
          return color_;
        }
        /**
         * <code>.Demo.Color color = 1;</code>
         * @param value The enum numeric value on the wire for color to set.
         * @return This builder for chaining.
         */
        public Builder setColorValue(int value) {
          color_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>.Demo.Color color = 1;</code>
         * @return The color.
         */
        public DemoProtoBuf.Demo.Color getColor() {
          @SuppressWarnings("deprecation")
          DemoProtoBuf.Demo.Color result = DemoProtoBuf.Demo.Color.valueOf(color_);
          return result == null ? DemoProtoBuf.Demo.Color.UNRECOGNIZED : result;
        }
        /**
         * <code>.Demo.Color color = 1;</code>
         * @param value The color to set.
         * @return This builder for chaining.
         */
        public Builder setColor(DemoProtoBuf.Demo.Color value) {
          if (value == null) {
            throw new NullPointerException();
          }

          color_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>.Demo.Color color = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearColor() {

          color_ = 0;
          onChanged();
          return this;
        }

        private int messageData_ ;
        /**
         * <code>int32 messageData = 2;</code>
         * @return The messageData.
         */
        public int getMessageData() {
          return messageData_;
        }
        /**
         * <code>int32 messageData = 2;</code>
         * @param value The messageData to set.
         * @return This builder for chaining.
         */
        public Builder setMessageData(int value) {

          messageData_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 messageData = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearMessageData() {

          messageData_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Demo.DemoMessage)
      }

      // @@protoc_insertion_point(class_scope:Demo.DemoMessage)
      private static final DemoProtoBuf.Demo.DemoMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new DemoProtoBuf.Demo.DemoMessage();
      }

      public static DemoProtoBuf.Demo.DemoMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DemoMessage>
          PARSER = new com.google.protobuf.AbstractParser<DemoMessage>() {
        @Override
        public DemoMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoMessage(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DemoMessage> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<DemoMessage> getParserForType() {
        return PARSER;
      }

      @Override
      public DemoProtoBuf.Demo.DemoMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 默认就是singular  最多出现1次
     * </pre>
     *
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private volatile Object value_;
    /**
     * <code>string value = 2;</code>
     * @return The value.
     */
    public String getValue() {
      Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>string value = 2;</code>
     * @return The bytes for value.
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LIKES_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList likes_;
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @return A list containing the likes.
     */
    public com.google.protobuf.ProtocolStringList
        getLikesList() {
      return likes_;
    }
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @return The count of likes.
     */
    public int getLikesCount() {
      return likes_.size();
    }
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @param index The index of the element to return.
     * @return The likes at the given index.
     */
    public String getLikes(int index) {
      return likes_.get(index);
    }
    /**
     * <pre>
     * 可以 出现 0 次 1 次 多次
     * </pre>
     *
     * <code>repeated string likes = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the likes at the given index.
     */
    public com.google.protobuf.ByteString
        getLikesBytes(int index) {
      return likes_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, value_);
      }
      for (int i = 0; i < likes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, likes_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, value_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < likes_.size(); i++) {
          dataSize += computeStringSizeNoTag(likes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getLikesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DemoProtoBuf.Demo)) {
        return super.equals(obj);
      }
      DemoProtoBuf.Demo other = (DemoProtoBuf.Demo) obj;

      if (getId()
          != other.getId()) return false;
      if (!getValue()
          .equals(other.getValue())) return false;
      if (!getLikesList()
          .equals(other.getLikesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      if (getLikesCount() > 0) {
        hash = (37 * hash) + LIKES_FIELD_NUMBER;
        hash = (53 * hash) + getLikesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DemoProtoBuf.Demo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProtoBuf.Demo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProtoBuf.Demo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProtoBuf.Demo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProtoBuf.Demo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DemoProtoBuf.Demo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DemoProtoBuf.Demo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DemoProtoBuf.Demo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DemoProtoBuf.Demo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DemoProtoBuf.Demo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DemoProtoBuf.Demo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DemoProtoBuf.Demo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DemoProtoBuf.Demo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 每个字段必须要有编号，并且不允许重复
     * </pre>
     *
     * Protobuf type {@code Demo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Demo)
        DemoProtoBuf.DemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DemoProtoBuf.internal_static_Demo_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DemoProtoBuf.internal_static_Demo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DemoProtoBuf.Demo.class, DemoProtoBuf.Demo.Builder.class);
      }

      // Construct using com.demo.protobuf.DemoProtoBuf.Demo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        value_ = "";

        likes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DemoProtoBuf.internal_static_Demo_descriptor;
      }

      @Override
      public DemoProtoBuf.Demo getDefaultInstanceForType() {
        return DemoProtoBuf.Demo.getDefaultInstance();
      }

      @Override
      public DemoProtoBuf.Demo build() {
        DemoProtoBuf.Demo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DemoProtoBuf.Demo buildPartial() {
        DemoProtoBuf.Demo result = new DemoProtoBuf.Demo(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.value_ = value_;
        if (((bitField0_ & 0x00000001) != 0)) {
          likes_ = likes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.likes_ = likes_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DemoProtoBuf.Demo) {
          return mergeFrom((DemoProtoBuf.Demo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DemoProtoBuf.Demo other) {
        if (other == DemoProtoBuf.Demo.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        if (!other.likes_.isEmpty()) {
          if (likes_.isEmpty()) {
            likes_ = other.likes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLikesIsMutable();
            likes_.addAll(other.likes_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DemoProtoBuf.Demo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DemoProtoBuf.Demo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * 默认就是singular  最多出现1次
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 默认就是singular  最多出现1次
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 默认就是singular  最多出现1次
       * </pre>
       *
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = 0;
        onChanged();
        return this;
      }

      private Object value_ = "";
      /**
       * <code>string value = 2;</code>
       * @return The value.
       */
      public String getValue() {
        Object ref = value_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @return The bytes for value.
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string value = 2;</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {

        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>string value = 2;</code>
       * @param value The bytes for value to set.
       * @return This builder for chaining.
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        value_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList likes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLikesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          likes_ = new com.google.protobuf.LazyStringArrayList(likes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @return A list containing the likes.
       */
      public com.google.protobuf.ProtocolStringList
          getLikesList() {
        return likes_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @return The count of likes.
       */
      public int getLikesCount() {
        return likes_.size();
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param index The index of the element to return.
       * @return The likes at the given index.
       */
      public String getLikes(int index) {
        return likes_.get(index);
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the likes at the given index.
       */
      public com.google.protobuf.ByteString
          getLikesBytes(int index) {
        return likes_.getByteString(index);
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param index The index to set the value at.
       * @param value The likes to set.
       * @return This builder for chaining.
       */
      public Builder setLikes(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLikesIsMutable();
        likes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param value The likes to add.
       * @return This builder for chaining.
       */
      public Builder addLikes(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLikesIsMutable();
        likes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param values The likes to add.
       * @return This builder for chaining.
       */
      public Builder addAllLikes(
          Iterable<String> values) {
        ensureLikesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, likes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLikes() {
        likes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 可以 出现 0 次 1 次 多次
       * </pre>
       *
       * <code>repeated string likes = 3;</code>
       * @param value The bytes of the likes to add.
       * @return This builder for chaining.
       */
      public Builder addLikesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureLikesIsMutable();
        likes_.add(value);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Demo)
    }

    // @@protoc_insertion_point(class_scope:Demo)
    private static final DemoProtoBuf.Demo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DemoProtoBuf.Demo();
    }

    public static DemoProtoBuf.Demo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo>
        PARSER = new com.google.protobuf.AbstractParser<Demo>() {
      @Override
      public Demo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Demo> getParserForType() {
      return PARSER;
    }

    @Override
    public DemoProtoBuf.Demo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Demo_DemoMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Demo_DemoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\ndemo.proto\"\254\001\n\004Demo\022\n\n\002id\030\001 \001(\005\022\r\n\005val" +
      "ue\030\002 \001(\t\022\r\n\005likes\030\003 \003(\t\032>\n\013DemoMessage\022\032" +
      "\n\005color\030\001 \001(\0162\013.Demo.Color\022\023\n\013messageDat" +
      "a\030\002 \001(\005\":\n\005Color\022\007\n\003RED\020\000\022\010\n\004BLUE\020\007\"\004\010\003\020" +
      "\003\"\004\010\004\020\004\"\004\010\005\020\005*\005BLACK*\005WHITEB!\n\021com.demo." +
      "protobufB\014DemoProtoBufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Demo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Demo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_descriptor,
        new String[] { "Id", "Value", "Likes", });
    internal_static_Demo_DemoMessage_descriptor =
      internal_static_Demo_descriptor.getNestedTypes().get(0);
    internal_static_Demo_DemoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Demo_DemoMessage_descriptor,
        new String[] { "Color", "MessageData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
